### ISSUE TITLE
请问可以提供完整的训练代码吗

### ISSUE THREAD

**Issue by swjtulinxi** [liumency/DSAMNet#1]

**Comment by swjtulinxi** [comment]
请问为什么我用stanet的训练代码，训练这个网络，总是和论文有几个点的差距呢？能不能提供完整的训练代码啊

**Comment by liumency** [comment]
> 请问为什么我用stanet的训练代码，训练这个网络，总是和论文有几个点的差距呢？能不能提供完整的训练代码啊

已上传

**Comment by swjtulinxi** [comment]
用你这个就更差了，开始很高，约训练越低
![image](https://user-images.githubusercontent.com/50089266/145313898-4dddaf9a-a0ef-4a11-9b4d-8d98d248a57a.png)

**Comment by liumency** [comment]
> 用你这个就更差了，开始很高，约训练越低 ![image](https://user-images.githubusercontent.com/50089266/145313898-4dddaf9a-a0ef-4a11-9b4d-8d98d248a57a.png)

你好，模型收敛比较快，可以提前中止训练，用验证集上精度最高的模型即可

**Comment by liumency** [comment]
> 用你这个就更差了，开始很高，约训练越低 ![image](https://user-images.githubusercontent.com/50089266/145313898-4dddaf9a-a0ef-4a11-9b4d-8d98d248a57a.png)

你好，模型收敛比较快，可以考虑提前中止训练，用验证集上精度最高的模型进行测试

**Comment by swjtulinxi** [comment]
但是第三轮的时候就0.60了，还是达不到论文的精度，我用自己写的代码都还可以达到0.626

**Comment by liumency** [comment]
> 但是第三轮的时候就0.60了，还是达不到论文的精度，我用自己写的代码都还可以达到0.626

您好，刚刚检查了一下代码，将model/dsamnet.py的ratio参数按原文修改了默认值。如有需要，可以重新下载尝试。很抱歉给您带来的不便，也非常感谢您的反馈。

**Comment by liumency** [comment]
> 但是第三轮的时候就0.60了，还是达不到论文的精度，我用自己写的代码都还可以达到0.626

您好，刚刚检查了一下代码，将model/dsamnet.py的ratio参数按原文修改了默认值，同时修改了train_options.py的初始学习率。如有需要，可以重新下载尝试。很抱歉给您带来的不便，也非常感谢您的反馈。

**Comment by liumency** [comment]
> 但是第三轮的时候就0.60了，还是达不到论文的精度，我用自己写的代码都还可以达到0.626

您好，刚刚检查了一下代码，将model/dsamnet.py的ratio参数按原文修改了默认值，同时修改了train_options.py的初始学习率。如有需要，可以重新下载尝试。很抱歉给您带来的不便，也非常感谢您的反馈。

**Comment by swjtulinxi** [comment]
感谢，我发现这种基于distance度量的变化检测方式非常不稳定，stanet也是一样，受学习率影响非常大，而且感觉只能用adam，用上sgd直接爆炸。我用孪生网络分类的方式，用nn.BCEloss + diceloss，训练你这个数据集可以达到0.66

**Comment by liumency** [comment]
> 感谢，我发现这种基于distance度量的变化检测方式非常不稳定，stanet也是一样，受学习率影响非常大，而且感觉只能用adam，用上sgd直接爆炸。我用孪生网络分类的方式，用nn.BCEloss + diceloss，训练你这个数据集可以达到0.66

好的~感谢分享^_^

**Comment by swjtulinxi** [comment]
现在倒是稳定多了，一直在0.62左右徘徊，感觉还是很难达到论文效果

**Comment by zzjdsy** [comment]
请问一下，用nn.BCELoss是不是在BCL.py中将距离映射在0~1之间然后就可以计算BCELoss损失了？
